version: '3'
services:
  # Changing the name as everybody used the same application names...
  app-sha256:
    build: .
    ports:
     - "8085:8085"
    links:
      - redis
  redis:
    image: redis
    command: redis-server --save 60 1
    volumes:
      - data:/data
    restart: always
    ports:
     - "6379:6379"
volumes:
  data:
